### ISSUE TITLE
Call for maintainers

### ISSUE THREAD

**Issue by zol** [percolatestudio/meteor-migrations#59]
Since I'm no longer actively developing an app that uses `migrations`, I've lost touch with the codebase and the project. I'm looking for folks to take over development and maintenance, please raise your hand if you're interested.

**Comment by npu3paka** [comment]
I can continue if you want to. I will make sure it will work with the latest version with no problems.

**Comment by zol** [comment]
Thanks! I'll add you as a collaborator to the repository.

**Comment by npu3paka** [comment]
Thank you man :)

**Comment by emmanuelbuah** [comment]
I'd like to help but interested in making an node npm package that can be used in a none meteor project. Let me know if its possible with the current standing and if not, I'd be happy to turn it into an npm package for generic node application without dependency on meteor.

**Comment by hexsprite** [comment]
@zol I'm still using this package, would be happy to help maintain.

**Comment by zol** [comment]
@emmanuelbuah Turning this into an Npm package would be great but I fear probably tricky to do well because of the tight Mongo dependency.

**Comment by zol** [comment]
Thanks for helping out @hexsprite . I've added you to the repo.

**Comment by emmanuelbuah** [comment]
Totally agree. I already forked and made the changes for an npm package. I will publish it in a few. I think a plug-in architecture can be implemented with ease to support other storage types. 

I looked at other migration packages such as https://github.com/okv/east but decided to convert your package into an npm package due to the auto migration (forward or backwards) nature. Most of the migration packages out there require explicitly using an up or down/rollback API to perform migration instead of auto detecting and migration to the right version based on the current version.

**Comment by zol** [comment]
@emmanuelbuah Awesome, thanks for working on that!

**Comment by hexsprite** [comment]
@emmanuelbuah maybe this package can be refactored to use the npm package as a dependency instead then...

**Comment by emmanuelbuah** [comment]
Certainly. I will let you know when I check in my changes. 

Emmanuel Quame Buah

https://twitter.com/emmanuelbuah

On Wed, Oct 12, 2016 at 12:26 PM Jordan Brant Baker

<
mailto:Jordan Brant Baker <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

https://github.com/emmanuelbuah
maybe this package can be refactored to use the npm package as a dependency instead then...

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/percolatestudio/meteor-migrations/issues/59#issuecomment-253280481
, or

**Comment by emmanuelbuah** [comment]
Hi, sorry this took much much longer than expected. Finally got around to it. I have refactored the package and published it at https://www.npmjs.com/package/mgdb-migrator and https://github.com/emmanuelbuah/mgdb-migrator. Cheers!

**Comment by defionscode** [comment]
Curious, since @hexsprite and @npu3paka have become maintainers (assumed from this thread) why is this issue still open and why is there still a call for maintainers on the README?

**Comment by emmanuelbuah** [comment]
Close away!

**Comment by dburles** [comment]
@emmanuelbuah nice work, happy to put a link to your version in the readme

**Comment by emmanuelbuah** [comment]
Sure. Thanks. Let me know if there's anything else I can do to help

**Comment by dburles** [comment]
Thanks, will close the thread for now
